accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login$', 'accounts.views.persona_login', name='persona_login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
)

betterCode/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
    url(r'^$', 'lists.views.home_page', name='home'),
    url(r'^lists/', include('lists.urls')),
    url(r'^accounts/', include('accounts.urls')),
)

lists/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^(\d+)/$', 'lists.views.view_list', name='view_list'),
    url(r'^new$', 'lists.views.new_list', name='new_list'),
    url(r'^users/(.+)/$', 'lists.views.my_lists', name='my_lists'),
)

accounts/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone


class User(models.Model):
    email = models.EmailField(primary_key=True)
    last_login = models.DateTimeField(default=timezone.now)
    REQUIRED_FIELDS = ()
    USERNAME_FIELD = 'email'

    def is_authenticated(self):
        return True

lists/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

    @property
    def name(self):
        return self.item_set.first().text


@python_2_unicode_compatible
class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    def __str__(self):
        return self.text

    class Meta:
        unique_together = ('list', 'text')
        order_with_respect_to = 'list'

lists/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.exceptions import ValidationError
from django.forms.utils import ErrorList

from lists.models import Item, List

__author__ = 'yooyoung-mo'

EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = u'이미 리스트에 해당 아이템이 있습니다'


class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': u'작업 아이템 입력',
                'class': 'form-control input-lg',
                'id': 'id_new_item'
            })
        }
        error_messages = {
            'text': {'required': EMPTY_LIST_ERROR}
        }


class NewListForm(ItemForm):
    def save(self, owner):
        if owner.is_authenticated():
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, data=None, files=None, auto_id='id_%s', prefix=None, initial=None, error_class=ErrorList,
                 label_suffix=None, empty_permitted=False, instance=None):
        super(ExistingListItemForm, self).__init__(data, files, auto_id, prefix, initial, error_class, label_suffix,
                                                   empty_permitted, instance)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse


def persona_login(request):
    user = authenticate(assertion=request.POST['assertion'])
    if user:
        login(request, user)
    return HttpResponse('OK')

lists/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect

from lists.forms import ItemForm, ExistingListItemForm, NewListForm
from lists.models import List

User = get_user_model()


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, 'form': form})

#
# def new_list(request):
#     form = NewListForm(data=request.POST)
#     if form.is_valid():
#         list_ = List()
#         if request.user.is_authenticated():
#             list_.owner = request.user
#         list_.save()
#         form.save(for_list=list_)
#         return redirect(list_)
#     else:
#         return render(request, 'home.html', {'form': form})


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

lists/templates/base.html
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <title>To-Do lists</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-default">
        <a class="navbar-brand" href="/">Superlists</a>
        {% if user.email %}
            <ul class="nav navbar-nav">
                <li><a href="{% url 'my_lists' user.email %}">나의 목록</a> </li>
            </ul>
            <a class="btn navbar-btn navbar-right" id="id_logout" href="{% url 'logout' %}">로그아웃</a>
            <span class="navbar-text navbar-right">로그인됨{{ user.email }}</span>
        {% else %}
            <a class="btn navbar-btn navbar-right" id="id_login" href="#">로그인</a>
        {% endif %}
    </nav>

    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>
                {% block list_form %}
                <form method="post" action="{% block form_action %}{% endblock %}">
                    {{ form.text }}
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="form-group has-error">
                            <span class="help-block">{{ form.text.errors }}</span>
                        </div>
                    {% endif %}
                </form>
                {% endblock %}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block extra_content %}
            {% endblock %}
        </div>
    </div>
</div>

<script src="http://code.jquery.com/jquery.min.js"></script>
<script src="https://login.persona.org/include.js"></script>
<script src="/static/list.js"></script>
<script src="/static/accounts.js"></script>
<script>
    $(document).ready(function() {
        var user = "{{ user.email }}" || null;
        var token = "{{ csrf_token }}";
        var urls = {
            login: "{% url 'persona_login' %}",
            logout: "TODO"
        };
        Superlists.Accounts.initialize(navigator, user, token, urls)

    });
</script>

</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}
{% block header_text %}작업 목록 시작{% endblock %}
{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}
{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}{% url 'view_list' list.id %}{% endblock %}
{% block table %}
    <table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
        <tr>
            <td>{{ forloop.counter }}: {{ item.text }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}나의 목록{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li>
                <a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}